/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:bd7f5095-0641-40d9-bd9e-ab3cee2269d4",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_V0exu2UZ0",
  aws_user_pools_web_client_id: "5l03s0ele6m469nqfr7h20i6jv",
  oauth: {
    domain: "rootsui65cc9b49-65cc9b49-staging.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "exp://10.0.0.8:19000",
    redirectSignOut: "exp://10.0.0.8:19000",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["GIVEN_NAME", "EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
